package constant

/*
 * running status constant
 * 运行状态常量
 */
const (
	RUNNING_STATUS_UNPREPARED int8 = 0
	RUNNING_STATUS_PREPARING  int8 = 1
	RUNNING_STATUS_PREPARED   int8 = 2
	RUNNING_STATUS_STARTING   int8 = 3
	RUNNING_STATUS_STARTED    int8 = 4
	RUNNING_STATUS_PAUSING    int8 = 5
	RUNNING_STATUS_PAUSED     int8 = 6
	RUNNING_STATUS_STOPPING   int8 = 7
	RUNNING_STATUS_STOPPED    int8 = 8

	RUNNING_STATUS_UNPREPARED_DESC = "Unprepared(未准备)"
	RUNNING_STATUS_PREPARING_DESC  = "Preparing(准备中)"
	RUNNING_STATUS_PREPARED_DESC   = "Prapared(已准备)"
	RUNNING_STATUS_STARTING_DESC   = "Starting(开始中)"
	RUNNING_STATUS_STARTED_DESC    = "Started(已开始)"
	RUNNING_STATUS_PAUSING_DESC    = "Pausing(暂停中)"
	RUNNING_STATUS_PAUSED_DESC     = "Paused(已暂停)"
	RUNNING_STATUS_STOPPING_DESC   = "Stopping(终止中)"
	RUNNING_STATUS_STOPPED_DESC    = "Stopped(已终止)"
)

var (
	//running status
	GlobalArrRunningStatus = []int8{
		RUNNING_STATUS_UNPREPARED,
		RUNNING_STATUS_PREPARING,
		RUNNING_STATUS_PREPARED,
		RUNNING_STATUS_STARTING,
		RUNNING_STATUS_STARTED,
		RUNNING_STATUS_PAUSING,
		RUNNING_STATUS_PAUSED,
		RUNNING_STATUS_STOPPING,
		RUNNING_STATUS_STOPPED,
	}

	GlobalArrRunningStatusDesc = map[int8]string{
		RUNNING_STATUS_UNPREPARED: RUNNING_STATUS_UNPREPARED_DESC,
		RUNNING_STATUS_PREPARING:  RUNNING_STATUS_PREPARING_DESC,
		RUNNING_STATUS_PREPARED:   RUNNING_STATUS_PREPARED_DESC,
		RUNNING_STATUS_STARTING:   RUNNING_STATUS_STARTING_DESC,
		RUNNING_STATUS_STARTED:    RUNNING_STATUS_STARTED_DESC,
		RUNNING_STATUS_PAUSING:    RUNNING_STATUS_PAUSING_DESC,
		RUNNING_STATUS_PAUSED:     RUNNING_STATUS_PAUSED_DESC,
		RUNNING_STATUS_STOPPING:   RUNNING_STATUS_STOPPING_DESC,
		RUNNING_STATUS_STOPPED:    RUNNING_STATUS_STOPPED_DESC,
	}
)
